import type { Metadata } from "next";
import { lilitaOne, montserrat, nunito, rubikGemstones } from "./fonts/fonts";
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";

// // Load Poppins font
// const poppins = Poppins({
//   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
//   subsets: ['latin', 'latin-ext'],
//   variable: '--font-poppins', // Optional: create a CSS variable
// });

// // Load Lilita One font
// const lilitaOne = Lilita_One({
//   weight: ['400'], // Only one weight is available
//   subsets: ['latin'],
//   variable: '--font-lilita', // Optional: create a CSS variable
// });

export const metadata: Metadata = {
  title: "Bookie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${lilitaOne.className} ${rubikGemstones.className} ${montserrat.className} antialiased`}>
        <ResponsiveNav />
        {children}
      </body>
    </html>
  );
}
